name: qrcode
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  intl: ^0.15.8
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.9+5
  firebase_storage: ^3.1.6
  image_picker: ^0.6.7+12
  liquid_swipe: ^1.5.0
  shared_preferences: ^0.5.12+2
  cupertino_icons: ^0.1.2
  barcode_scan: ^2.0.1
  qr_flutter: ^3.2.0
  path_provider: ^1.6.5
  simple_animations: ^1.3.3
  flutter_speed_dial: ^1.2.5
  local_auth: ^0.4.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/slideImage.png
    - assets/slideImage2.png
    - assets/user.png
